### ISSUE TITLE
Error TS2304: Cannot find name 'Blob'

### ISSUE THREAD

**Issue by kurdykartur** [Stuk/jszip#693]
The error started to occur after an update from 3.3.0 to 3.4.0 (and exist in 3.5.0 also) in our Typescript application. Adding the DOM to tsconfig.json fixes the problem but DOM is not needed in a backend application. We are using nodejs ver. 12.

**Comment by cainlevy** [comment]
We tried downgrading but ultimately ended up with a custom type file.

1) tell TypeScript where to find custom typings

in `tsconfig.json`:

```json
{
  "compilerOptions": {
    "typeRoots": ["./node_modules/@types", "./types"]
  }
}
```

2. declare type stub

in `./types/Blob/index.d.ts`:

```typescript
type Blob = never
```

**Comment by pkruk2** [comment]
I'm also getting this error - I'm using JSZip in custom extension for vscode

**Comment by pacholoamit** [comment]
We're facing the same issues on our end as well

**Comment by XinwenCheng** [comment]
Hi @pacholoamit , this issue still exists in 3.10.1.
