### PR TITLE
Fix browser module resolution

### LINKED ISSUE #477: "Error: cannot find module 'stream'" when using Chrome
On my Windows Home desktop, I install jszip 3.1.4 with NPM and open this html file with Google Chrome browser (Version 61.0.3163.100 (Official Build) (64-bit)):
```
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="node_modules/jszip/dist/jszip.js" ></script>
</head>
<body>
<p>Hello</p>
</body>
</html>
```
Result: "Error: cannot find module 'stream'"

Problem does not occur with Firefox, MS IE, or MS Edge.

Similar to what @mitchwilson found in [Issue #464](https://github.com/Stuk/jszip/issues/464), when I comment out line #1709 `module.exports = require("stream");` it works fine. I'm using jszip on client side.

### LINKED ISSUE #521: How can I use jszip with Expo (React Native) ?
I get "unable to resolve module 'stream' when I try to use jszip in an Expo app.Expo is a javascript only version of React Native.

### LINKED ISSUE #524: Can't resolve 'stream'
Hello. After updating the version of Angular to 6.0 I got the next error. 
```ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream' 
Did anyone have the same?

### PR DESCRIPTION
**Pull request by mgechev**
When webpack/rollup or another bundler, implementing the
[`browser-resolve`](https://www.npmjs.com/package/browser-resolve)
spec tries to resolve `jszip` for a browser-based project they fail
with:

```
ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream' in '/node_modules/jszip/lib'
```

Since you already produce a browser build, we just need to point to
it inside of `package.json`'s `browser` field.

PS: You'd probably want to double check the semantics of `"."`.

Looking at `browser-resolve` it seems that everything will work
as expected. Also, trying empirically with webpack, everything worked
out, but few more pairs of eyes would be greatly appreciated.

Also @sokra should be able to share a valuable opinion.

Fix #524
Fix #521
Fix #477

### CODE REVIEW

**Comment by mgechev** [comment]
@Stuk the build seems to be timing out. Doesn't look related to the change.

**Comment by hakimio** [comment]
@Stuk can you merge this, so we could build Angular 8 apps using jszip?

**Comment by Stuk** [comment]
Thanks for the PR! I just tried bundling JSZip with webpack and parcel and had no issues.

This is my testing `package.json`:

```json
{
  "name": "jszip-package-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jszip": "^3.2.2",
    "parcel-bundler": "^1.12.3",
    "webpack": "^4.39.3",
    "webpack-cli": "^3.3.8"
  }
}
```

Both `./node_modules/.bin/webpack index.js` and `./node_modules/.bin/parcel build index.js` completed successfully.

Could you create a package.json, or repository that reproduces the issue?

**Comment by mgechev** [comment]
[Here it is](https://github.com/mgechev/jszip-repro). Run:

```
npm i && npm run build
```

**Comment by Stuk** [comment]
Thanks! I can repro. I need to understand the impact of this PR on Webpack/Browserify/Parcel etc. bundles.

I think it might increase bundle sizes for folks, because there could be 2 stream implementations in the bundle: 1 in the JSZip dist, and another one added by the bundler.

If you're able to help me understand the impact, I'd very much appreciate it.

**Comment by eduboxgithub** [comment]
I'm using Angular 8 and the latest version of jszip and I'm seeing the same error when I build my project:

> Module not found: Error: Can't resolve 'stream'

If the error cames from the file deadable-stream-browser.js

```
/*
 * This file is used by module bundlers (browserify/webpack/etc) when
 * including a stream implementation. We use "readable-stream" to get a
 * consistent behavior between nodejs versions but bundlers often have a shim
 * for "stream". Using this shim greatly improve the compatibility and greatly
 * reduce the final size of the bundle (only one stream implementation, not
 * two).
 */
module.exports = require("stream");
```

**Comment by ialex90** [comment]
Hi @Stuk is there any news on this? is it possible to merge this PR?
I'm having error in the CI and with the angular build.
Thanks!

**Comment by Stuk** [comment]
Just spent some time checking that this doesn't adversely affect webpack or parcel, and it looks like it's ok. [Tested here](https://travis-ci.org/github/Stuk/jszip/builds/669787166)

**Comment by Stuk** [comment]
Published at v3.3.0
